import type { Metadata } from "next";
import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — Deus Performance",
  description:
    "Terms governing use of Deus Performance — the adaptive training engine operated by Riz Management LLC.",
};

const EFFECTIVE_DATE = "28 June 2026";
const GOVERNING_LAW = "the State of Delaware, United States";

const SECTIONS = [
  {
    id: "agreement",
    title: "Agreement to These Terms",
    body: [
      "These Terms of Service are a legally binding agreement between you and Riz Management LLC (\"Deus Performance,\" \"we,\" \"us,\" \"our\") governing your access to and use of the website at deusperformance.com and the associated training programme generation service (collectively, the \"Service\").",
      "By accessing the Service, submitting the assessment, or generating a training programme, you confirm that you have read, understood, and agreed to these Terms. If you do not agree, do not use the Service.",
    ],
    items: null as string[] | null,
    warning: null as string[] | null,
    footer: null as string | null,
  },
  {
    id: "eligibility",
    title: "Eligibility",
    body: [
      "You must be at least 13 years of age to use the Service. By using the Service, you represent and warrant that you meet this requirement.",
      "Users between the ages of 13 and 17 should use the Service with the knowledge and consent of a parent or legal guardian. If you are a parent or guardian who becomes aware that your minor child has submitted personal information without your consent, contact us immediately.",
      "By using the Service, you also represent that you have the legal capacity to enter into a binding agreement in your jurisdiction.",
    ],
    items: null as string[] | null,
    warning: null as string[] | null,
    footer: null as string | null,
  },
  {
    id: "not-medical",
    title: "Not Medical Advice",
    body: [
      "Deus Performance is a practice of performance education. The training programmes generated by the Service are produced by an automated constraint-based engine and, in some configurations, an AI language model. They are provided for informational and educational purposes only.",
    ],
    items: null as string[] | null,
    warning: [
      "The Service does not constitute medical advice, medical diagnosis, rehabilitation guidance, or clinical treatment of any kind.",
      "The injury-accommodation features of the Service route programming around selected body parts using approved exercise substitutions — this is not a substitute for professional clinical evaluation or physical therapy.",
      "Always consult a licensed physician, sports medicine professional, or certified clinician before beginning or modifying any exercise programme, particularly if you have existing injuries, chronic conditions, or medical history that may affect exercise safety.",
      "The information provided is not intended to replace the advice of a qualified health professional. Reliance on any information provided by the Service is solely at your own risk.",
    ],
    footer: null as string | null,
  },
  {
    id: "description",
    title: "Description of the Service",
    body: [
      "Deus Performance provides a free automated assessment that collects your physical profile, goals, schedule, and current state, then generates a weekly strength and conditioning programme governed by hard constraints (CNS load management, movement pattern coverage, volume limits, and fatigue-adaptive adjustments).",
      "The Service is provided as-is at no charge for the assessment tier. Paid engagement tiers (Foundation, Practice, Stewardship) may be offered separately and are subject to additional terms communicated at the time of purchase.",
    ],
    items: null as string[] | null,
    warning: null as string[] | null,
    footer: null as string | null,
  },
  {
    id: "user-responsibilities",
    title: "Your Responsibilities",
    body: ["You agree to:"],
    items: [
      "Provide accurate, current, and complete information in the assessment. The quality of your programme depends entirely on the accuracy of your inputs.",
      "Use the Service only for lawful purposes and in accordance with these Terms.",
      "Not attempt to reverse-engineer, disassemble, scrape, or extract the engine's constraint rules, exercise library, or other proprietary content at scale.",
      "Not use automated means to submit multiple assessments, probe the API, or circumvent usage limits.",
      "Not submit false health information with the intent to obtain a programme that misrepresents your physical state.",
      "Report any security vulnerabilities or data issues you discover through our Correspondence page rather than exploiting them.",
    ],
    warning: null as string[] | null,
    footer: null as string | null,
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    body: [
      "All content on the Deus Performance website — including the engine architecture, constraint rules, exercise library, editorial content (Dispatches), design system, and programme output structure — is the intellectual property of Riz Management LLC, protected by copyright and other applicable law.",
      "The personalised training programme generated for you is provided for your personal, non-commercial use. You may not redistribute, resell, or sublicense programme outputs without express written permission.",
      "Your submitted assessment data remains your information. We do not claim ownership over data you provide — see our Privacy Policy for how it is handled.",
    ],
    items: null as string[] | null,
    warning: null as string[] | null,
    footer: null as string | null,
  },
  {
    id: "disclaimer",
    title: "Disclaimer of Warranties",
    body: [
      "THE SERVICE IS PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, RIZ MANAGEMENT LLC EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:",
    ],
    items: [
      "Implied warranties of merchantability, fitness for a particular purpose, and non-infringement.",
      "Any warranty that the Service will meet your requirements or achieve any particular fitness or performance result.",
      "Any warranty that the Service will be uninterrupted, timely, secure, or error-free.",
      "Any warranty regarding the accuracy or completeness of AI-generated exercise selections.",
    ],
    warning: null as string[] | null,
    footer:
      "Exercise carries inherent risk. Results depend on individual factors including genetics, effort, consistency, nutrition, sleep, and adherence — none of which the Service controls.",
  },
  {
    id: "liability",
    title: "Limitation of Liability",
    body: [
      "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL RIZ MANAGEMENT LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY:",
    ],
    items: [
      "Indirect, incidental, special, consequential, or punitive damages.",
      "Loss of profits, data, goodwill, or other intangible losses.",
      "Physical injury, illness, or harm arising from exercise performed in reliance on generated programmes.",
      "Damages arising from service interruptions, data loss, or third-party actions.",
    ],
    warning: null as string[] | null,
    footer:
      "Our total aggregate liability to you for any claim arising from or related to the Service shall not exceed the greater of (a) the amount you paid us in the 12 months preceding the claim or (b) USD $50. Some jurisdictions do not allow limitations on liability for personal injury or implied warranties — in such jurisdictions, our liability is limited to the minimum extent permitted by law.",
  },
  {
    id: "indemnification",
    title: "Indemnification",
    body: [
      "You agree to indemnify, defend, and hold harmless Riz Management LLC and its affiliates, officers, agents, and employees from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or in any way connected with your access to or use of the Service, your violation of these Terms, or your violation of any third-party rights.",
    ],
    items: null as string[] | null,
    warning: null as string[] | null,
    footer: null as string | null,
  },
  {
    id: "governing-law",
    title: "Governing Law and Disputes",
    body: [
      `These Terms shall be governed by and construed in accordance with the laws of ${GOVERNING_LAW}, without regard to its conflict of law provisions.`,
      "Any dispute arising under or relating to these Terms or the Service shall first be addressed by contacting us in good faith. If the dispute cannot be resolved informally within 30 days, it shall be submitted to binding arbitration under the rules of a mutually agreed arbitration body, except that either party may seek injunctive relief in a court of competent jurisdiction to protect intellectual property or confidential information.",
      "Nothing in this clause prevents you from asserting your rights under applicable consumer protection or data protection laws in your jurisdiction.",
    ],
    items: null as string[] | null,
    warning: null as string[] | null,
    footer: null as string | null,
  },
  {
    id: "termination",
    title: "Termination and Suspension",
    body: [
      "We reserve the right to suspend or terminate your access to the Service at any time, without notice, if we determine that you have violated these Terms, are misusing the Service, or if we are required to do so by law.",
      "You may stop using the Service at any time. Sections of these Terms that by their nature should survive termination (including Disclaimer of Warranties, Limitation of Liability, and Indemnification) shall survive.",
    ],
    items: null as string[] | null,
    warning: null as string[] | null,
    footer: null as string | null,
  },
  {
    id: "changes",
    title: "Changes to These Terms",
    body: [
      "We may modify these Terms from time to time. Material changes will be indicated by an updated effective date. We encourage you to review this page periodically.",
      "Your continued use of the Service following any update constitutes your acceptance of the revised Terms. If you do not agree to revised Terms, stop using the Service.",
    ],
    items: null as string[] | null,
    warning: null as string[] | null,
    footer: null as string | null,
  },
];

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="pt-[58px]">
        <section className="mx-auto max-w-[860px] px-5 py-[52px] md:px-[32px]">
          <div className="kicker mb-[14px]">Legal</div>
          <h1
            className="font-play font-normal leading-[0.97] tracking-[-0.02em] mb-[16px] text-ink"
            style={{ fontSize: "clamp(36px, 5vw, 68px)" }}
          >
            Terms of <em className="text-warm">Service.</em>
          </h1>
          <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink3 mb-[36px]">
            Effective date — {EFFECTIVE_DATE} · Riz Management LLC
          </p>

          {/* Health warning banner */}
          <div className="border border-[rgba(184,68,68,0.35)] bg-[rgba(184,68,68,0.06)] px-[20px] py-[18px] mb-[48px]">
            <p className="font-mono text-[8px] uppercase tracking-[0.22em] text-danger mb-[8px]">
              Health &amp; Safety Notice
            </p>
            <p className="font-bask text-[13px] text-ink2 leading-[1.8]">
              Deus Performance is a performance education service. It is{" "}
              <strong className="text-ink font-bold">not</strong> a medical
              provider and does not offer medical advice, diagnosis, or clinical
              treatment. Consult a licensed clinician before beginning any new
              training programme.
            </p>
          </div>

          {/* Table of contents */}
          <nav
            aria-label="Terms contents"
            className="mb-[52px] border border-line bg-bg1 px-[24px] py-[22px]"
          >
            <p className="font-mono text-[8px] uppercase tracking-[0.22em] text-ink3 mb-[14px]">
              Contents
            </p>
            <ol className="flex flex-col gap-[6px]">
              {SECTIONS.map((s, i) => (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    className="font-mono text-[9px] uppercase tracking-[0.1em] text-accent hover:text-ink transition-colors"
                  >
                    {i + 1}. {s.title}
                  </a>
                </li>
              ))}
              <li>
                <a
                  href="#contact-terms"
                  className="font-mono text-[9px] uppercase tracking-[0.1em] text-accent hover:text-ink transition-colors"
                >
                  {SECTIONS.length + 1}. Contact
                </a>
              </li>
            </ol>
          </nav>

          <div className="flex flex-col gap-[48px]">
            {SECTIONS.map((s, i) => (
              <section key={s.id} id={s.id}>
                <h2 className="font-mono text-[10px] uppercase tracking-[0.22em] text-accent mb-[6px]">
                  {i + 1}.
                </h2>
                <h3 className="font-play font-normal text-[22px] text-ink mb-[16px] leading-[1.2]">
                  {s.title}
                </h3>
                {s.body.map((p, pi) => (
                  <p
                    key={pi}
                    className="font-bask text-[14px] text-ink2 leading-[1.85] mb-[12px]"
                  >
                    {p}
                  </p>
                ))}
                {s.warning && (
                  <ul className="flex flex-col gap-[8px] border border-[rgba(184,68,68,0.3)] bg-[rgba(184,68,68,0.04)] px-[20px] py-[18px] my-[16px]">
                    {s.warning.map((item, wi) => (
                      <li key={wi} className="flex items-start gap-[10px]">
                        <span
                          aria-hidden="true"
                          className="shrink-0 text-danger mt-[1px] font-mono text-[10px]"
                        >
                          —
                        </span>
                        <span className="font-bask text-[13px] text-ink2 leading-[1.75]">
                          {item}
                        </span>
                      </li>
                    ))}
                  </ul>
                )}
                {s.items && (
                  <ul className="flex flex-col gap-[8px] border border-line bg-bg1 px-[20px] py-[18px] my-[16px]">
                    {s.items.map((item, ii) => (
                      <li key={ii} className="flex items-start gap-[10px]">
                        <span
                          aria-hidden="true"
                          className="shrink-0 text-accent mt-[1px] font-mono text-[10px]"
                        >
                          —
                        </span>
                        <span className="font-bask text-[13px] text-ink2 leading-[1.75]">
                          {item}
                        </span>
                      </li>
                    ))}
                  </ul>
                )}
                {s.footer && (
                  <p className="font-bask text-[14px] text-ink2 leading-[1.85] mt-[12px]">
                    {s.footer}
                  </p>
                )}
              </section>
            ))}

            {/* Contact */}
            <section id="contact-terms">
              <h2 className="font-mono text-[10px] uppercase tracking-[0.22em] text-accent mb-[6px]">
                {SECTIONS.length + 1}.
              </h2>
              <h3 className="font-play font-normal text-[22px] text-ink mb-[16px] leading-[1.2]">
                Contact
              </h3>
              <p className="font-bask text-[14px] text-ink2 leading-[1.85] mb-[16px]">
                Questions about these Terms, or notices required under them,
                should be sent to:
              </p>
              <div className="border border-line bg-bg1 px-[20px] py-[18px] mb-[24px]">
                <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink3 mb-[4px]">
                  Legal contact
                </p>
                <p className="font-bask text-[14px] text-ink mb-[16px]">
                  Riz Management LLC · Deus Performance
                </p>
                <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink3 mb-[4px]">
                  Email
                </p>
                <p className="font-bask text-[14px] text-ink mb-[16px]">
                  legal@deusperformance.com
                </p>
                <p className="font-mono text-[9px] uppercase tracking-[0.18em] text-ink3 mb-[4px]">
                  Web
                </p>
                <Link
                  href="/correspondence"
                  className="font-bask text-[14px] text-accent hover:text-ink transition-colors"
                >
                  deusperformance.com/correspondence
                </Link>
              </div>
            </section>
          </div>

          <hr className="border-0 h-px bg-line my-[52px]" />
          <div className="flex gap-6">
            <Link href="/privacy" className="btn-ghost text-[10px]">
              Privacy Policy &#8594;
            </Link>
            <Link href="/assess" className="btn-ghost text-[10px]">
              Begin Assessment &#8594;
            </Link>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
